server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_share?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    #配置连接池
    hikari: #springboot自带的连接池，速度快
      pool-name: EshareDataPool
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000ms(10分钟)
      maximum-pool-size: 180000
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000(30分钟)
      max-lifetime: 1800000
      #连接超时时，默认是30000(30秒)
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

#Mybatis-插件配置


# Mybatis SQL 打印（方法接口所在包）
logging:
  level:
    com.cjw.eshare.dao: debug

#jwt配置
jwt:
  # JWT存储的请求头
  tokenHeader: Authorization
  #JWT 加解密使用的密钥
  secret: yeb-secret
  #JWT的超期限时间
  expiration: 604800
  #JWT 负载中拿到开头
  tokenHead: Bearer
